### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by treylon** [AsyncHttpClient/async-http-client#816] opened 2015-02-10 10:25 UTC
When I try to create a new AsyncHttpClient I get the following error:

<code>
Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: Didn't find class "sun.security.util.HostnameChecker"

</code>
it is caused by this line of code:
<code>
        AsyncHttpClient c = new AsyncHttpClient();
</code>

Any ideas on this issue?

**Comment by slandelle** [comment] 2015-02-10 10:48
You're probably running on Android. Issue is already fixed and will be shipped in upcoming 1.9.9.

Duplicate of #810

**Closed by slandelle** 2015-02-10 10:48 UTC

**Comment by treylon** [comment] 2015-02-12 10:41
Thanks a lot! Is there already a planned release date?

**Comment by treylon** [comment] 2015-02-12 10:54
Yes I am using android but I am still getting the same error on 1.9.9! 

Any ideas?
And could you reopen the issue?

**Comment by slandelle** [comment] 2015-02-12 13:56
1.9.10 is wait to be synced on maven central. Note that you have to either use the Netty provider, or disable security and set acceptAnyCertificate.
