### ISSUE TITLE
Possible memory leak issue (v 2.0.11)

### ISSUE THREAD

**Issue by tbrenna** [AsyncHttpClient/async-http-client#1234] opened 2016-08-23 02:55 UTC
We are using version 2.0.11 of the library on a high throughput system running with a 6GB heap on Java 8. Most of the connections we make are designed to be short-lived (less than 150ms.) The system seems to be fine at first but then we run out of memory at high traffic after about 24 hours, due to creation and non-garbage-collection of netty and nio objects, for example the DefaultHandle object count goes higher and higher.) I don't believe there is anything unusual about how we are using the async http client. We were using version 1.9 until very recently. We are using thread pools for this work, which then make connections through the async http client library. Are you aware of a memory leak issue? Any help would be appreciated.

Our usage is like this:

(On startup, in our "AsyncHttpClientManager" Spring singleton - we have 5 of these for different kinds of connections, this one has the most traffic):
```java
httpClient = new DefaultAsyncHttpClientConfig.Builder() 
                .setConnectTimeout(connectTimeout) //75
                .setRequestTimeout(requestTimeout) //145
                .setReadTimeout(readTimeout) //300
                .setConnectionTtl(pooledConnectionIdleTimeout) //500
                .setPooledConnectionIdleTimeout(pooledConnectionIdleTimeout) //500
                .setMaxConnections(maximumConnectionsTotal) //20000
                .setMaxConnectionsPerHost(maximumConnectionsPerHost) //5000
                .setThreadFactory(new NamedThreadFactory("AsyncHttpClient")).build();
```
(During runtime)
```java
class RecipientClient extends AsyncCompletionHandler<Response> {
...
public void connect() {
   Request request = new RequestBuilder()
                .setMethod("GET")
                .setAddress(recipient.getInfo().getRecipAddr())
                .setUrl(urlWithParams.toString())
                .setHeader(HttpHeaders.Names.HOST, recipient.getInfo().getRecipHost())
                .setHeader(HttpHeaders.Names.CONNECTION, "keep-alive")
                .build();
   future = httpClient.executeRequest(request, this);
}
...
public Response onCompleted(Response response) {
   //Parse some JSON and put the results in a list object.
}

public void onThrowable(Throwable t) {
   //Log an error and put the error in a list object.
}
```
(On shutdown)
```java
httpClient.close();
```

**Comment by slandelle** [comment] 2016-08-23 05:53
Could you please either provide a heap dump, or the roots to GC, please?

**Comment by slandelle** [comment] 2016-08-23 06:54
Could you also please upgrade to AHC 2.0.12 that upgrades to Netty 4.0.40? The [Recycler default capacity change](https://github.com/netty/netty/pull/5589) could help.

**Comment by tbrenna** [comment] 2016-08-23 12:02
This is what the memory profile looks like after 24 hours, with millions of netty-related objects in memory. As far as 2.0.12, we haven't load tested it yet, although I have tried a limited test of 2.1.0-alpha1, and that seemed to exhibit the same behavior of not garbage collecting old objects:
![image](https://cloud.githubusercontent.com/assets/17504789/17891099/19c5dbca-68f7-11e6-93d6-e3ad0a459ebb.png)

**Comment by tbrenna** [comment] 2016-08-23 12:05
<img width="1137" alt="memoryprofile" src="https://cloud.githubusercontent.com/assets/17504789/17891204/90fe43e4-68f7-11e6-915a-678fa7801b8e.png">

**Comment by slandelle** [comment] 2016-08-23 12:12
@tbrenna I really think you should try AHC 2.0.12 with the latest Netty 4.0.40.
Then, I suspect you might be writing too fast for your IO and you'd have to implement back pressure.

cc @normanmaurer

**Comment by hauberteric** [comment] 2016-08-24 19:02
I have run some tests with AHC 2.0.12 & Netty 4.0.40.
The results seem to be tied to using a ThreadPoolExecutor.  When I spawn 10 threads myself and have them all use the client, things are stable.  In fact, there is no Recycler activity at all after initialization.  Using a fixed size ThreadPoolExecutor, the leak of Recycler$DefaultHandle & Recycler$WeakOrderQueue$Link is steady.  The below code is what I used to verify this behavior.  I tried to take a heapdump after the object count from the below code running with 100k+ 'leaked' objects.  The GC triggered by the heap dump was able to clean up all but 4k of the objects.  Thanks.

`public class Main {

    private static AsyncHttpClientConfig buildAsyncHttpClientConfig() {
        return new DefaultAsyncHttpClientConfig.Builder()
                .setConnectTimeout(200)
                .setRequestTimeout(200)
                .setReadTimeout(200)
                .setConnectionTtl(500)
                .setPooledConnectionIdleTimeout(500)
                .setMaxConnections(20000)
                .setMaxConnectionsPerHost(10000)
                .build();
    }

    public static void main(String[]args) throws Exception {
        System.out.println("Starting Client init");
        try(DefaultAsyncHttpClient httpClient = new DefaultAsyncHttpClient(buildAsyncHttpClientConfig());) {
            System.out.println("Client init Complete!");
            threadPoolExec(httpClient); //shows leak
//            manualThreads(httpClient); //no leak
        }
    }


    private static void threadPoolExec(DefaultAsyncHttpClient httpClient) throws InterruptedException {
        System.out.println("Thread Pool");
        ThreadPoolExecutor exec = new ThreadPoolExecutor(10, 10, 500, TimeUnit.SECONDS, new ArrayBlockingQueue<Runnable>(200));
            while(true) {
                Thread.sleep(1);
                exec.execute(() -> {
                    Future<Response> result = httpClient.executeRequest(prepareRequest(), new RtbCallback());
                    try {
                        result.get();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                });
            }
    }
    private static void manualThreads(DefaultAsyncHttpClient httpClient){
        System.out.println("ManualThreads");
        for(int j = 0; j < 10; j++){
            final int q = j;
            Thread thread = new Thread(() -> {
                while(true){
                    try {
                        Future<Response> result = httpClient.executeRequest(prepareRequest(), new RtbCallback());
                        result.get();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            thread.setDaemon(true);
            thread.start();
        }

        while(true){}
    }

    private static final String JSON ="{}";

    protected static Request prepareRequest() {
        return new RequestBuilder()
                .setMethod("POST")
                .setUrl("http://localhost:8090/test")
                .setBody(JSON.getBytes())
                .setCharset(Charset.forName("UTF-8"))
                .setHeader(HttpHeaders.Names.CONTENT_TYPE, "application/json")
                .build();
    }
}`

**Comment by hauberteric** [comment] 2016-08-24 19:46
It looks like this issue is describing what we have found or something very near. 
https://github.com/netty/netty/issues/5299

**Comment by slandelle** [comment] 2016-08-24 20:24
@hauberteric Why do you have a `Thread.sleep(1)` in `threadPoolExec` that you don't have in `manualThreads `?

**Comment by hauberteric** [comment] 2016-08-29 22:18
Good catch. I think that sleep might be the real culprit now.  I am not sure why that would cause recycler activity but I don't have a very in depth knowledge on Netty's details.

**Comment by slandelle** [comment] 2016-08-29 22:24
What's for sure is that your 2 tests don't do the same thing, at all.
Because of the Thread.sleep, the first one only send 1 request per second, while the second one send as many requests as possible with ~10 concurrent connections.

**Comment by hauberteric** [comment] 2016-08-30 14:52
I am not sure what you mean about 1 request per second.  1000 requests get submitted to the queue per second.  

The comparison may be invalid, but the code is able to reproduce what is seen in our production application reliably on my machine.  We are not sure how to proceed.

**Comment by slandelle** [comment] 2016-08-30 22:17
@hauberteric I've been running your `threadPoolExec` test against current master (i.e. Netty 4.0.41) on my laptop (OSX 10.11.6, jdk 1.8.0_102), have performed 5 heap dumps and can't reproduce your issue.

The heap and non heap usage is super stable, so does it the number of `Recycler$DefaultHandle[]` is stable (~400 after full GC).

<img width="753" alt="screen shot 2016-08-31 at 00 14 27" src="https://cloud.githubusercontent.com/assets/849197/18109144/f6af65d8-6f0f-11e6-83b1-c22d8f6a2fa0.png">

<img width="1170" alt="screen shot 2016-08-31 at 00 17 07" src="https://cloud.githubusercontent.com/assets/849197/18109212/4a1cd91c-6f10-11e6-8298-35f6d23fc1bd.png">

Closing as "can't reproduce".

**Closed by slandelle** 2016-08-30 22:17 UTC
