### ISSUE TITLE
Send file

### ISSUE THREAD

**Issue by danilomagrini** [AsyncHttpClient/async-http-client#1452] opened 2017-08-16 21:54 UTC
How I do that: 
`curl -i -X POST -H "Content-Type: multipart/form-data" -F "file=@/xxxx/arquivo/teste.jpg" "https://api.mercadolibre.com/messages/attachments?access_token=XXXXXXXXXXXXXXXXX"`

with AsyncHttpClient?

I tried:
`http.preparePost(apiUrl + path)
                .addHeader("Content-Type", "multipart/form-data")
                .addBodyPart(new FilePart(fileName, new File(filePath), "application/octet-stream")
                .setQueryParams(params);`

But I receive from server: {"message":"File attachment must not be empty","error":"bad_request","status":400,"cause":[]}

Yes, I'm sure that filePath is correct! And "new File(filePath)" is OK.

With Postman works fine!
![captura de tela de 2017-08-16 18-44-10](https://user-images.githubusercontent.com/1017788/29386945-47b574be-82b4-11e7-8a0b-077b13ad3b5f.png)

**Comment by slandelle** [comment] 2017-08-16 22:19
Please provide an actionable reproducer, there's no way to help without one.

**Comment by slandelle** [comment] 2017-08-26 23:44
Gentle ping. Can you please provide a way to reproduce your issue? Also, which AHC version do you use?

**Comment by danilomagrini** [comment] 2017-08-27 02:54
Sorry, but the recipient requires registration and paid oauth2 authentication.

**Comment by slandelle** [comment] 2017-08-27 08:08
I've compared the multipart payloads from AHC and curl on my own server, and could only spot the following differences (which shouldn't matter):
* AHC (actually Netty) HTTP header names are lowercase, while curl uses capitalized names (eg `content-length` vs `Content-Length`)
* curl multipart boundaries are shorter
* user-agent header value (I've seen some servers having a white list of user-agents, with curl being accepted and not AHC, plain stupid)

Try to do the same thing and compare your HTTP payloads, eg with CharlesProxy.

Closing for now as I can't reproduce. Feel free to ping if you can provide more information.

**Closed by slandelle** 2017-08-27 08:08 UTC
