### ISSUE TITLE
Problem with custom headers in ByteArrayPart

### ISSUE THREAD

**Issue by alepulver** [AsyncHttpClient/async-http-client#1247] opened 2016-09-12 18:09 UTC
First, when adding a new header with addCustomHeader("name", "value"), one would expect "name: value" to be appended to the output but instead just "namevalue" is used. This forces the developer to arbitrarily add the separator inside the name or the value.

Second, some headers passed in the constructor aren't recognized in addCustomHeader. For example addCustomHeader("Content-Type", "text/plain") doesn't replace the corresponding header but adds another one. One could check for each of these special ones but programatically it's difficult to use.

Third, and most importantly, it's not possible to completely control the Content-Disposition header. It always tries to build it from 2 parts (dispositionType and name), and to get exactly a string one has to include everything in the first and set the second one to null.

These issues will be addressed in a PR.

**Comment by slandelle** [comment] 2016-09-12 19:39
> First, when adding a new header with addCustomHeader("name", "value"), one would expect "name: value" to be appended to the output but instead just "namevalue" is used. This forces the developer to arbitrarily add the separator inside the name or the value.

Agree

> Second, some headers passed in the constructor aren't recognized in addCustomHeader. For example addCustomHeader("Content-Type", "text/plain") doesn't replace the corresponding header but adds another one. One could check for each of these special ones but programatically it's difficult to use.

Here, I tend to disagree with the expected behavior. `customHeaders` is intended for non standard headers, not for overriding standard ones that are already defined as final in the constructor. I'm not fond of providing multiple ways to do the same thing.  I'd rather detect those invalid override tentatives and throw an Exception.

> Third, and most importantly, it's not possible to completely control the Content-Disposition header. It always tries to build it from 2 parts (dispositionType and name), and to get exactly a string one has to include everything in the first and set the second one to null.

Ok

**Comment by alepulver** [comment] 2016-09-12 19:56
> Here, I tend to disagree with the expected behavior. customHeaders is intended for non standard headers, not for overriding standard ones that are already defined as final in the constructor. I'm not fond of providing multiple ways to do the same thing. I'd rather detect those invalid override tentatives and throw an Exception.

Yes. But in practice the user would have to check that when receiving a map of headers and trying to construct a part object with them. In that case at least a constant list of "special" headers should be defined.

Also, I see two cases covered by the same constructor: high level parameter specification (like name and disposition type) and custom definition of headers (like setCustomContentDisposition). The user shouldn't be forced to choose the first two if he's going to override them later. Should we have two kind of constructors (or static methods)?

**Comment by slandelle** [comment] 2016-09-12 20:21
> when receiving a map of headers and trying to construct a part object with them

It looks to me that you're trying to build your own API with its own logic.

`setCustomContentDisposition` was only introduced for dealing with non standard headers. Not for a generic way to set all the headers.

**Comment by slandelle** [comment] 2016-09-13 13:41
Giving more thoughts about it, I think we would benefit of an immutable class with a single constructor + a builder.

**Comment by slandelle** [comment] 2016-09-13 14:59
FTR, the missing separator issue only exists in 1.9. [AHC is fine](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/request/body/multipart/part/MultipartPart.java#L311).

**Comment by slandelle** [comment] 2016-10-05 12:36
Closing as "won't fix":
* Missing separator issue only happens in AHC1 that has reached EOL
* Using `addCustomHeader` to add standard headers is a misusage
* Setting full "Content-Disposition" will be addressed in #1263

**Closed by slandelle** 2016-10-05 12:36 UTC
