### ISSUE TITLE
StreamedResponsePublisher cancelled() does not close the channel properly.

### ISSUE THREAD

**Issue by vsabella** [AsyncHttpClient/async-http-client#1456] opened 2017-09-01 02:49 UTC
StreamedResponsePublisher does not cancel the channel properly.

in https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/handler/StreamedResponsePublisher.java 

We are using play-ws client which wraps AsyncHttpClient. When streams are cancelled (such as the downloader cancelling their download) we notice the following:

1. this.logger.debug("Subscriber cancelled, ignoring the rest of the body"); is called - so the publisher does know that the stream is cancelled.

However, it does not result in Connection.close.  
The callback is registered here (https://github.com/AsyncHttpClient/async-http-client/blob/90124a5caf414658d537799116c7d4f3d1ad45dd/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L407) 
But it is never called, never resulting in a channel closed exception.

KeepAlive is false and we have the various connection pool timeouts at 15 seconds.

Also it appears that the callback is set as an attribute on the channel - is that the correct approach or is it possible to have the callback overwritten by more incoming data or another thread?

Any thoughts?

**Comment by slandelle** [comment] 2017-09-01 05:36
This is a duplicate of #1306, which is fixed in the 2.1 branch.

IIRC, the fix was pretty complex and the WebSocket code in AHC 2.1 is quite different from 2.0, so it would require some work to backport, and I don't have the cycles.
If one would provide a PR, I would gladly merge though.

**Comment by vsabella** [comment] 2017-09-01 14:54
@slandelle I don't mind getting a backported fix in however I don't think these are the same issue. The connection doesn't even attempt to drain (this isnt an infinite connection) and close, it simply never closes. It doesn't matter if its a tiny file being transferred or an infinite stream.

This looks more like a race condition on the attributes where the handler written for cancellation to the attribute is overwritten again by other activity? We can get connections to close by having a debugger change the order of execution - or it could be our misunderstanding of what we saw late at night.

Is it possible to reopen this issue so we have something to reference to for a backported fix?

**Comment by slandelle** [comment] 2017-09-01 16:22
> however I don't think these are the same issue

If would be great if you could provide a reproducer.

> Is it possible to reopen this issue so we have something to reference to for a backported fix?

Done

**Comment by HKrausAxon** [comment] 2017-09-06 15:28
The main issue seems to be that the current implementation assumes that AsyncHttpClientHandler.channelRead will be called again even after a connection has been killed - which is not the case.
This leads to the registered OnLastHttpContentCallback never being executed.

Is there any reason to register the callback to the Channel's default attribute rather than directly executing it on HandlerPublisher.cancelled() ?
It seems more straight forward and seems to achieve the intended result.

**Comment by slandelle** [comment] 2017-09-06 15:31
@HKrausAxon Sorry, I can't answer myself (this was a contribution), and I'm pretty swamped atm. cc @jroper

**Comment by HKrausAxon** [comment] 2017-09-06 15:59
I think this is a solution that would work better with most network stacks:
https://github.com/HKrausAxon/async-http-client/commit/44bbfdd5e272488d2fbf02396d4659380051d60e
Would be great if @jroper can chime in though, as I want to make sure this won't break anything else I'm not thinking about.

**Comment by jroper** [comment] 2017-09-07 06:24
If you offer the channel straight back to the pool without draining, then what will happen if a subscriber cancels before all the body has been received? The connections will go back into the pool, then another request will come and take it out of the pool, send a request down, but the body from the cancelled request will still be arriving, so instead of getting an HTTP response, it's going to get this body that it isn't interested in.

I think what we need to do is track if the end of the response has been received, if it hasn't, then drain and offer back to the pool, otherwise, hand it straight back to the pool as your change has done.

**Comment by slandelle** [comment] 2017-09-07 07:33
@jroper Actually, behavior will change in AHC 2.1 and ABORT will close the channel. I think the code can be cleaned up and there's no need to drain now.

**Comment by slandelle** [comment] 2017-09-07 07:50
See finishUpdate clean up in 6a2de0f433e7bb0587a2100c0589b9bd449d275f.

Now, I've checked the remaining paths to `drainChannelAndOffer` and it can't be dropped as @HKrausAxon suggests. For example, we need to drain the channel (= wait for the last response chunk) after a redirect or a ResponseFilter.

In order to get this fixed, the first step is to provide a **test case**.

**Comment by HKrausAxon** [comment] 2017-09-07 14:18
Sorry @slandelle - as you suggested I had originally posted a revision with a direct change to drainChannelAndOffer, which as you pointed out would have unintended side effects.
I had edited that post with a better version that doesn't have those issues shortly after (see above).

If we want to be more conservative, to avoid the scenario jroper@ described, we could also only change this behavior in case keepAlive is set to false, so no risk of the canceled response sending more data.

As for a test case: I'll yet have to figure out a proper way to simulate the drop of a socket in a unit test (ctrl+c on a client - not something that'll actively invoke any callbacks on the socket).
A manual test case is simple though, if that'll help!
Set up a StreamedResponsePublisher, start curling its output and ctrl+c that curl.
On effectively all Linux machines and ~half the Macs we have tested this on so far, this will lead to a leaked network socket (netstat -natp to confirm)

**Comment by HKrausAxon** [comment] 2017-09-08 16:07
Just to clarify on my past comment regarding jroper's concerns, I was thinking along the lines of this:
https://github.com/HKrausAxon/async-http-client/commit/f622636381e4d1602059d7c99e986d600b7080b9

**Comment by slandelle** [comment] 2017-09-13 15:54
@HKrausAxon Why not just always close the channel when the stream is cancelled?

**Comment by HKrausAxon** [comment] 2017-09-13 16:06
@slandelle From what I originally understood from @jroper I think the reasoning was that the channel might get returned to the pool and then send data from the previous connection.
However, I just realized that the drain method also checks channel.isActive(), which should already always be false in the cancellation case.

Which means we'd be back to this approach, which would directly throw it back: https://github.com/HKrausAxon/async-http-client/commit/9f28c703480a583e637735a2373ea896b93b4b2f
We could also directly call channelManager.closeChannel(channel); in StreamedResponsePublisher if you'd prefer that (slightly more straight forward and should lead to the same result)

**Comment by slandelle** [comment] 2017-09-13 16:15
> We could also directly call channelManager.closeChannel(channel); in StreamedResponsePublisher if you'd prefer that (slightly more straight forward and should lead to the same result)

Yes, that's exactly what I'm suggesting. Then, as I'm not a heavy stream user atm, I'd be interested in getting feedback on this. Do people have use cases where they heavily cancel streams but expect to be able to reuse the sockets?

**Comment by HKrausAxon** [comment] 2017-09-13 16:41
I've never seen it used like that (reusing a canceled stream socket in general doesn't sound like a very likely scenario) - but there could always be someone using it that way.

That being said, unless there's any data that suggests it'd be a bad idea, would you be okay with me creating pull requests on 2.0 and master with the proposed change?
Would it also be okay to bump the minor version in 2.0? (I'll then get in touch with PlayWS and hopefully get them to bump their dependency)

**Comment by slandelle** [comment] 2017-09-13 18:47
Sure. Let's just wait a few days for @jroper to maybe chime in.

**Comment by HKrausAxon** [comment] 2017-09-15 11:44
Hi @slandelle - since we haven't heard from James in a bit, I went ahead and created pull requests for 2.0 and master.
Assuming they look okay and get merged - I unfortunately have no idea how to publish the new 2.0 version. I assume some publishing step has to be triggered before the version gets bumped?
Should that version bump be a separate commit, and if so do you want me to create another PR for it or would you prefer to just go ahead and git push one from your end?

Thanks!

(For reference, links to the PRs are:
master: https://github.com/AsyncHttpClient/async-http-client/pull/1458
2.0: https://github.com/AsyncHttpClient/async-http-client/pull/1459 )

**Comment by slandelle** [comment] 2017-09-15 13:38
> I unfortunately have no idea how to publish the new 2.0 version.

I'll be the one bumping an releasing.

**Comment by HKrausAxon** [comment] 2017-09-15 14:49
> I'll be the one bumping an releasing.
Perfect, thanks! :)

**Comment by slandelle** [comment] 2017-09-15 16:20
Closed by bade99201f116f1ab7f0df20cee3c188b370a512 on master and 461afd841a73b2bfb14861b535beb8fd042d5c81 on 2.0.

**Closed by slandelle** 2017-09-15 16:20 UTC
Labels: Defect

**Comment by HKrausAxon** [comment] 2017-09-15 16:22
Thanks Stéphane, much appreciated!! :)
