### ISSUE TITLE
StackOverFlowError 

### ISSUE THREAD

**Issue by ykotikov** [AsyncHttpClient/async-http-client#1608] opened 2019-01-29 14:24 UTC
Hello

I have the following **client configuration**
```
Dsl.config().setRequestTimeout(60000)
        .setHandshakeTimeout(10000)
        .setMaxRequestRetry(2)
        .setConnectTimeout(3000)
         .setReadTimeout(3000)
        .setPooledConnectionIdleTimeout(60000)
        .setConnectionTtl(-1)
        .setMaxConnections(-1)
        .setMaxConnectionsPerHost(-1)
        .setUserAgent(null)
        .setFilterInsecureCipherSuites(false)
        .setValidateResponseHeaders(false)
        .setDisableUrlEncodingForBoundRequests(false)
        .setUseNativeTransport(false)
        .setIoThreadsCount(0)
        .setTcpNoDelay(true)
        .setThreadPoolName("ahc-client")
        .setConnectionPoolCleanerPeriod(1000)
```

**Java version** : 11
**Client version**: 2.6.0

I use  client for sending records to aws kinesis.  Sometimes I get Stackoverflow error under the load around 300 rps.

Here is **log output**

```
[DEBUG ] [loop-nio-2] o.a.AsyncCompletionHandler: https://kinesis.us-east-1.amazonaws.com:443
java.net.ConnectException: https://kinesis.us-east-1.amazonaws.com:443
at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:15
at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:33)
at org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:129)
at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onSuccess(NettyChannelConnector.java:92)
at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:26)
at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:616)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.StackOverflowError: null
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
 [DEBUG ] [loop-nio-2] o.a.n.h.HttpHandler: Channel Closed: [id: 0x035e16ca, L:0.0.0.0/0.0.0.0:53994] with attribute null
```

**Comment by slandelle** [comment] 2019-01-29 20:06
This bug could be anywhere, including the JDK, your own code, AHC, netty, and any other lib you have in your classpath.
What makes you think the issue is in AHC? Could you please provide a standalone reproducer that's only built on top of AHC and exhibits this issue?

**Comment by slandelle** [comment] 2019-01-29 20:15
Could you please provide a reproducer?

**Comment by nashley** [comment] 2019-03-14 16:02
I have also run into this on version `2.6.0` running on Java `11`.
[Here](https://gist.github.com/nashley/c6ddeb3771f6049d5c953efceb58db9b#file-async-http-client-log)'s the stacktrace.
I don't yet have steps to reproduce it, but I'll update if I do.

**Comment by slandelle** [comment] 2019-03-14 16:59
Thanks @nashley. Crossing fingers that you'll be able to come up with a reproducer, I have no idea what happens.

**Comment by nashley** [comment] 2019-03-14 18:08
[Here](https://gist.github.com/nashley/46c383cb70e29ee28afe9f0c5e3a5c86)'s another stacktrace from a different instance.
It's essentially the same, with:
```
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
at java.base/java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1033)
```
changing to:
```
at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1041)
at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1042)
```

**Comment by namiles** [comment] 2019-03-14 19:09
My initial thought is that somehow an `UnmodifiableCollection` wound up with itself as a delegate, but looking in the AHC and Netty repos, I don't see any questionable reflection happening that could cause that.

Looks like other people around the internet are [having](https://github.com/elastic/elasticsearch/issues/23604) similar [problems](https://stackoverflow.com/questions/45649351/javafx-bind-lista-bidirectional-to-listb-throws-stackoverflowerror) with `UnmodifiableCollection`.

My next guess would be that something is wrapping an `UnmodifiableCollection` inside a new `UnmodifiableCollection` enough times that calling a method on it blows the stack. Don't know what's doing it or even where the problem collection is coming from yet.

**Comment by slandelle** [comment] 2019-03-14 20:15
Do you guys use Cookies?

**Comment by slandelle** [comment] 2019-03-14 20:19
Note: statement in original report is incorrect: obviously Java version is not 8 (`java.base/java.util.Collections`).

**Comment by namiles** [comment] 2019-03-14 20:51
We have seen this happen using two different configs in two totally different applications (different physical hosts even). One is like this:
```java
@Bean
public AsyncHttpClient httpClient() {
    Builder config = Dsl.config()
            .setReadTimeout(5000)
            .setRequestTimeout(5000)
            .setConnectTimeout(5000)
            .setConnectionTtl(15000)
            .setCookieStore(null)
            .setFollowRedirect(true)
            .setMaxRedirects(3);

    return Dsl.asyncHttpClient(config);
}
```
and the other is like this:
```java
@Bean
public AsyncHttpClient httpClient() {
    return Dsl.asyncHttpClient();
}
```
In both cases, the client is initialized at startup time and used throughout the lifetime of the app, so we aren't looping on any of that stuff in the client config builder. The cookie thing could explain when we saw it in the application that uses the default config, but it has happened more often with the application that does `.setCookieStore(null)`.

It's probably worth noting that the most recent time this happened to us, it continued to happen for a very long time. So whatever collection was borked is apparently sticking around. We had the process up and doing that every time it sent a request (once per minute with no other traffic on the box) for about 12 hours. It has since stopped though. So apparently the bad collection doesn't stick around _forever_.

**Comment by slandelle** [comment] 2019-03-14 21:00
It might help getting a heap dump when this happens. We would then be able to figure out who is holding those UnmodifiableCollections.

**Comment by namiles** [comment] 2019-03-14 21:03
I'm planning on digging deep on this tomorrow. Will update here if I get any new info.

**Comment by slandelle** [comment] 2019-03-14 21:04
Thanks

**Comment by namiles** [comment] 2019-03-15 20:46
I didn't manage to reproduce this locally, but I have added the JVM arg `-XX:MaxJavaStackTraceDepth=0` to all of our dev environments. This stops stack traces from being truncated at the default of 1024 stack frames, so we should be able to see the full stack trace if this happens again.

@ykotikov, if you're still able to reproduce this issue relatively repeatably, it would be extremely helpful if you could use the `-XX:MaxJavaStackTraceDepth` option to get us a full stack trace.

**Comment by ykotikov** [comment] 2019-03-18 12:04
@nashley Sure, I'll try to reproduce it with this flag

**Comment by slandelle** [comment] 2019-03-18 12:38
This one looks like a pretty good suspect: https://bugs.openjdk.java.net/browse/JDK-8214129

**Comment by namiles** [comment] 2019-03-18 14:09
Yeah that JDK bug definitely lines up with what we're doing. Thousands of requests to the same TLS 1.2, SNI-using cluster of hosts.

Looks like it's fixed in JDK 12 and 11.0.3. 12 is supposed to drop tomorrow. Don't know about 11.0.3.

**Comment by slandelle** [comment] 2019-03-21 12:35
So:

- JDK 12 is out, most likely with the fix for this bug (I can't manage to find the bugfixes section in the release note)
- The fix is available in the JDK 11 nightly builds, that you can for example get from https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=hotspot
- JDK 11.0.3 should be out some time in April
- If one wants a certified build with the fix, you can probably get one from [jClarity](https://www.jclarity.com) 

I'm closing this for now as the JDK bug is the most likely culprit and there's nothing I can do on my side.

Please report if the JDK fix doesn't fix this issue.

**Closed by slandelle** 2019-03-21 12:35 UTC

**Comment by house0128** [comment] 2019-09-16 04:13
I meet same issue ,using jdk 11.0.2.@nmiles-bw @ykotikov did you finally solve this problem by upgrading the JDK to 11.0.3?
