### ISSUE TITLE
Expose ConnectionPool metrics for monitoring

### ISSUE THREAD

**Issue by ggarber** [AsyncHttpClient/async-http-client#1259] opened 2016-09-30 09:22 UTC
It would be good to expose some metrics (connectionsInUse/Free) so that we can use that information for monitoring purposes.

**Comment by slandelle** [comment] 2016-09-30 10:00
Duplicate of #1130 , wip in #1255

**Closed by slandelle** 2016-09-30 10:00 UTC

**Comment by skilledmonster** [comment] 2017-07-28 20:35
Is this change ever merged to the master. I am using the latest version and I don't see the getClientStats in the AsyncHttpClient Interface. How do I collect client stats?

**Comment by joprice** [comment] 2017-11-13 19:10
Could this be backported to 2.0.x?
