### ISSUE TITLE
com.ning.http.client.Body.close() Method is Not Called for FileBodyGenerator

### ISSUE THREAD

**Issue by pete-experimenter** [AsyncHttpClient/async-http-client#896] opened 2015-05-29 09:28 UTC
*Steps to Reproduce*
* Check out project https://github.com/pete-experimenter/async-client-generator-not-being-closed-test-project/
* Run
```sh
./gradlew clean test
```
* One test in *FileAfterUploadNotRemovedTest* should fail as can be seen on 
![image](https://cloud.githubusercontent.com/assets/6091200/7880036/426d3d76-060f-11e5-9500-af64ec3a7098.png)

For *InputStreamBodyGenerator* everything is fine.

**Comment by slandelle** [comment] 2015-05-29 09:34
@pete-experimenter It looks that you don't provide any provider (neither Netty not Grizzly), so you're falling back to the JDK provider, which is just a toy, isn't maintained, and which will be going away in AHC2.

Please try with a *real* provider.

Closing for now. Feel free to ping if you can reproduce with Netty or Grizzly.

**Closed by slandelle** 2015-05-29 09:34 UTC

**Comment by pete-experimenter** [comment] 2015-05-29 09:47
That was the quickest ticket resolution ever! :+1: 
Jokes aside I have committed a fix to configure client using Netty. Could you have a look? As it is still reproducible.

**Comment by slandelle** [comment] 2015-05-29 09:54
I guess [this](https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/generators/FileBodyGenerator.java#L28) should be moving in the javadoc.

**Comment by pete-experimenter** [comment] 2015-05-29 10:06
I have used Grizzly generator and the same behaviour. Please checkout the latest code - it uses both Netty & Grizzly Also, would appreciate if you could add to README.md that the below dependencies need to be added to be able to use Grizzly provider. Don't this it would hurt anybody :)
```sh
    compile 'org.glassfish.grizzly:grizzly-core:2.3.21'
    compile 'org.glassfish.grizzly:grizzly-http:2.3.21'
    compile 'org.glassfish.grizzly:grizzly-websockets:2.3.21'
    compile 'org.glassfish.grizzly:connection-pool:2.3.21'
```

**Comment by slandelle** [comment] 2015-05-29 10:08
I improved the javadoc in 1.9 to explain Netty provider's behavior and cleaned up class in master.

**Comment by pete-experimenter** [comment] 2015-05-29 10:08
@slandelle, thanks but taking into account what I have said before, what is the workaround?

**Comment by slandelle** [comment] 2015-05-29 10:15
@pete-experimenter The provided BodyGenerator implementations final in master should have been final. How they work are implementation details and the only guaranteed behavior is the one of the interface.

If you want to delete your file when upload is succeeded, you should be doing that either in the Handler's `onComplete`, or register a listener on the Future.

**Comment by pete-experimenter** [comment] 2015-05-29 10:20
@slandelle, my personal view is that providing an implementation that does work properly with any of the providers and saying "final" twice plus referring to some implementation to explain that is not a good resolution to me, but if you consider that's how it should be, then there is nothing I can do.

**Comment by slandelle** [comment] 2015-05-29 10:25
@pete-experimenter The real issue is that those classes were not meant for extension and should have been final in the first place.

**Comment by pete-experimenter** [comment] 2015-05-29 10:27
Depricate the classes then, as they don't work properly and are misleading. I have GB's of data left in temporary folder because of that.

**Comment by pete-experimenter** [comment] 2015-05-29 10:29
Are you going to update the README.md as I have commented above?

Also would appreciate if you could add to README.md that the below dependencies need to be added to be able to use Grizzly provider. Don't think it would hurt anybody :)
```
    compile 'org.glassfish.grizzly:grizzly-core:2.3.21'
    compile 'org.glassfish.grizzly:grizzly-http:2.3.21'
    compile 'org.glassfish.grizzly:grizzly-websockets:2.3.21'
    compile 'org.glassfish.grizzly:connection-pool:2.3.21'
```

**Comment by slandelle** [comment] 2015-05-29 10:33
Can't deprecate because passing a `FileBodyGenerator` is the only way to upload a File with `SimpleAsyncHttpClient`.

And can't make final in 1.9 without risking breaking existing code.

**Comment by pete-experimenter** [comment] 2015-05-29 10:38
Right, then I guess https://github.com/AsyncHttpClient/async-http-client/commit/7ce989b04d5f35693c6d54e3f17597dad28c4e15 is good enough. Thanks for your help.

**Comment by slandelle** [comment] 2015-05-29 10:41
I'm going to update the README.

Please understand that I inherited this project and spend quite some time filling holes everywhere, and that I only maintain the Netty provider, not the Grizzly one.

**Comment by pete-experimenter** [comment] 2015-05-29 10:43
Yep, understood. No worries. It is an excellent project I must admit, so thanks for it. Also the updates are so frequent, which is so rare.
So, a top notch project all in all!

**Comment by slandelle** [comment] 2015-05-29 10:59
Thanks for your kind words.
README improved, I hope it will prevent other users to run into the same pitfalls.

**Comment by pete-experimenter** [comment] 2015-05-29 11:01
Thanks!
