### ISSUE TITLE
AsyncHttpClient does not close sockets under heavy load (1.9 only)

### ISSUE THREAD

**Issue by wsargent** [AsyncHttpClient/async-http-client#1027] opened 2015-11-03 05:34 UTC
If you create 1000 requests in a very short time frame and use connection pool with AsyncHttpClient 1.9.21 and Netty 3.10.1, then some sockets will leak and stay open even past the idle socket reaper.  This was initially filed as https://github.com/playframework/playframework/issues/5215, but can be replicated without Play WS.

Created a reproducing test case here: https://github.com/wsargent/asynchttpclient-socket-leak

if you have 50 requests, then they'll all be closed immediately.
if you have 1000 requests, they'll stay open for a while.
After roughly two minutes, AHC will close off all idle sockets, but up to 30 will never die and will always be established.

To see the dangling sockets, run the id of the java process:

```
sudo lsof -i | grep 31602
```

You'll see

```
java      31602       wsargent   89u  IPv6 0xe1b25a8062380645      0t0  TCP 192.168.1.106:58646->ec2-54-173-126-144.compute-1.amazonaws.com:https (ESTABLISHED)
```

The client port number is your key into the application: if you search for "58646" in application.log, then you'll see that there's a connection associated with it:

```
2015-11-02 20:41:38,496 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in New I/O worker #1 - [id: 0x5650b318, /192.168.1.106:58646 => playframework.com/54.173.126.144:443] RECEIVED: BigEndianHeapChannelBuffer(ridx=0, widx=2357, cap=2357)
```

You can see the lifecycle of a handle by using grep:

```
grep "0x5650b318" application.log
```

and what's interesting is that while most ids will have a `CLOSE` / `CLOSED` lifecycle associated with them:

```
2015-11-02 20:41:45,878 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in Hashed wheel timer #1 - [id: 0x34804fcc, /192.168.1.106:59122 => playframework.com/54.173.126.144:443] WRITE: BigEndianHeapChannelBuffer(ridx=0, widx=69, cap=69)
2015-11-02 20:41:46,427 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in New I/O worker #2 - [id: 0x34804fcc, /192.168.1.106:59122 => playframework.com/54.173.126.144:443] CLOSE
2015-11-02 20:41:46,427 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in New I/O worker #2 - [id: 0x34804fcc, /192.168.1.106:59122 :> playframework.com/54.173.126.144:443] DISCONNECTED
2015-11-02 20:41:46,434 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in New I/O worker #2 - [id: 0x34804fcc, /192.168.1.106:59122 :> playframework.com/54.173.126.144:443] UNBOUND
2015-11-02 20:41:46,434 [DEBUG] from org.jboss.netty.handler.logging.LoggingHandler in New I/O worker #2 - [id: 0x34804fcc, /192.168.1.106:59122 :> playframework.com/54.173.126.144:443] CLOSED
```

In the case of "0x5650b318", there's no CLOSE event happening here.  In addition, there's a couple of lines that say it's a cached channel:

```
2015-11-02 20:41:33,340 [DEBUG] from com.ning.http.client.providers.netty.request.NettyRequestSender in default-akka.actor.default-dispatcher-4 - Using cached Channel [id: 0x5650b318, /192.168.1.106:58646 => playframework.com/54.173.126.144:443]
2015-11-02 20:41:33,340 [DEBUG] from com.ning.http.client.providers.netty.request.NettyRequestSender in default-akka.actor.default-dispatcher-4 - Using cached Channel [id: 0x5650b318, /192.168.1.106:58646 => playframework.com/54.173.126.144:443]
```

So I think Netty is not closing cached channels even if they are idle, in some circumstances.

**Comment by jroper** [comment] 2015-11-03 06:01
Do they ever go into `CLOSE_WAIT`? This is similar to an issue we saw here:

https://github.com/netty/netty/issues/3193

If they don't go into `CLOSE_WAIT`, then it's probably not related.

**Comment by saeta** [comment] 2015-11-03 06:35
I don't think they make it to `CLOSE_WAIT`.

**Comment by slandelle** [comment] 2015-11-03 11:23
@wsargent @jroper Have you tried upgrading to AHC 1.9.31 and Netty 3.10.5?

**Comment by slandelle** [comment] 2015-11-03 11:58
I could reproduce with AHC 1.9.31 and Netty 3.10.5.
But I definitively couldn't with AHC 2 w/ Netty 4 (~20 attempts).

This is going to be a fun one...

**Comment by jroper** [comment] 2015-11-05 04:59
@slandelle is this something that you're taking on yourself, or do you want us to help?

**Comment by slandelle** [comment] 2015-11-05 06:41
@jroper I'm really sorry, but I think I won't be able to investigate this myself before something like 2 weeks. swamped :weary: 
So yes, it would be great if you guys could land a hand. I can cut 1.9.32 when you want.

**Comment by francisdb** [comment] 2016-01-26 15:22
I guess playframework will just migrate to 2.x once it is released?

**Comment by slandelle** [comment] 2016-01-26 15:34
If they can live without backward compatibility, yes :)

**Comment by wsargent** [comment] 2016-01-26 18:22
working on it.  Right now looking at why Netty's HTTPHeaders don't have an equals method...

**Comment by slandelle** [comment] 2016-01-26 18:58
o_0
What would be the use case for that? That would be super expensive.

**Comment by wsargent** [comment] 2016-01-26 20:49
Testing header manipulation: https://github.com/playframework/playframework/blob/master/framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala#L93

**Comment by slandelle** [comment] 2016-01-26 21:00
Yeah, so that's not production code. I really suspect that equals and hashcode aren't implemented because such an implementation would be very slow and shouldn't be used for production code.

I suggest you write a custom spec2 matcher that takes care of the multiple sorting and the case insensitive comparisons.

**Comment by francisdb** [comment] 2016-01-26 21:51
Could this be related?

(Sentry output)
````
Future not in appropriate state %s, not closing

NettyResponseFuture{currentRetry=1, isDone=false, isCancelled=false, asyncHandler=play.api.libs.ws.ning.NingWSRequest$$anon$1@595b6919, nettyRequest=com.ning.http.client.providers.netty.request.NettyRequest@54f4d960, content=null, uri=https://xxx.xxx/data/, keepAlive=true, httpHeaders=null, exEx=null, redirectCount=0, timeoutsHolder=com.ning.http.client.providers.netty.request.timeout.TimeoutsHolder@52632c8d, inAuth=false, statusReceived=false, touch=181658236}

  Module "java.lang.Thread", line 745, in run
  Module "org.jboss.netty.util.ThreadRenamingRunnable", line 108, in run
  Module "org.jboss.netty.util.HashedWheelTimer$Worker", line 369, in run
  Module "org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket", line 632, in expireTimeouts
  Module "org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout", line 556, in expire
  Module "com.ning.http.client.providers.netty.channel.pool.DefaultChannelPool$IdleChannelDetector", line 208, in run
  Module "com.ning.http.client.providers.netty.channel.pool.DefaultChannelPool$IdleChannelDetector", line 169, in closeChannels
  Module "com.ning.http.client.providers.netty.channel.pool.DefaultChannelPool$IdleChannelDetector", line 155, in isChannelCloseable
```

**Comment by slandelle** [comment] 2016-01-26 22:00
This is very weird and is not supposed to happen. Would love a reproducer.

**Comment by francisdb** [comment] 2016-01-26 23:14
Well, can't reproduce but my guess is this happened during a large amount of parallel connections to the same https url. Could also be related to OOM or too many open files as we had similar issues the last few days.

**Comment by slandelle** [comment] 2016-01-27 07:23
@francisdb Frankly, I can't say anything about your issue without being able to reproduce. I develop AHC for Gatling, and next version will ship AHC2, so AHC1 is more or less EOL'ed. I'll only keep on merging pull requests from the community.

**Comment by francisdb** [comment] 2016-01-27 08:36
@slandelle totally understand, just wanted to share the trace in case it rang a bell
Thanks for this great project

**Comment by slandelle** [comment] 2016-01-27 08:48
@francisdb The meaning of your log is that a connection ended up in the pool while the last request that used it was still flying, which shouldn't be possible. So there's a race condition somewhere, but this somewhere can be anywhere...

Thanks for your kind words.

**Comment by SirBraneDamuj** [comment] 2016-02-25 18:58
I was observing similar behavior on 1.19.3

After a period of intense load, the connections used would not close, but would also not be reused. So I could oscillate between periods of heavy and light load and quickly accumulate unused, unclosed connections.

I updated to 1.19.33 and the problem stopped happening.

**Comment by slandelle** [comment] 2016-02-25 19:30
@SirBraneDamuj The version numbers you mention are wrong. I guess `1.19.33` is `1.9.33`, but is `1.19.3` actually `1.9.3` or something else?

I could reproduce this issue w/ `1.9.31`. I don't see any change in between that could be related. :(

**Comment by slandelle** [comment] 2016-02-25 19:35
@SirBraneDamuj Did your issue happened over https, or plain http? If the former, your issue was probably a different one: a [Netty issue](https://github.com/netty/netty/issues/4296) that was fixed in Netty `3.10.5` and shipped with AHC 1.9.33.

**Comment by SirBraneDamuj** [comment] 2016-02-25 19:39
Sorry for the version number mixup :) it was 1.9.3 to 1.9.33

Yeah it was plain HTTP. That's probably it then.

**Comment by slandelle** [comment] 2016-02-25 19:42
OK, thanks! So sadly, your issue was probably a different one.
Still, good for you :)

**Comment by slandelle** [comment] 2016-03-16 20:48
@francisdb Your issue was probably https://github.com/AsyncHttpClient/async-http-client/issues/1113, which just got fixed and released in AHC 1.9.35 and 2.0.0-beta13.

**Comment by slandelle** [comment] 2016-03-23 13:52
@wsargent Can you reproduce w/ 1.9.35?

**Comment by slandelle** [comment] 2016-03-23 13:54
@wsargent saw your comments/issues on the Play! bug tracker, so I guess this issue is indeed fixed. Closing now, feel free to ping if it's not.

**Closed by slandelle** 2016-03-23 13:54 UTC
Labels: Contributions Welcome!, Defect, Netty

**Comment by hilios** [comment] 2016-05-03 15:18
Still seeing this issue on my Akka Camel AHC application after some thousends of correct requests/responses cycles the `Too many open files`  appear and never get back.

**Comment by hilios** [comment] 2016-05-03 15:19
async-http-client = 1.9.35 
netty = 3.10.5.Final

**Comment by slandelle** [comment] 2016-05-03 16:14
Latest AHC is 2.0.2 and doesn't have the issue.
Please consider upgrading or contributing a fix.

**Comment by hilios** [comment] 2016-05-03 19:45
Great, since I am using Apache Camel I will do a PR to them updating their AsyncHttpClient. Thank you for the info.

**Comment by slandelle** [comment] 2016-05-03 19:50
Good luck :)

**Comment by anexplore** [comment] 2016-06-30 08:00
is it possible to set __child.keepAlive=true__ to solve this problem?

**Comment by harisankarh** [comment] 2017-03-24 15:04
@slandelle  Could you please tell if this issue is fixed in 1.9.40 ? Asking this because I found that 1.9.40 was released after 2.0.2 (2.0.2 has the fix as you mentioned). Actually, our client has a platform limitation of java 1.7 and is unable to upgrade to java 1.8 (found that 2.x requires java 1.8).  Thank you.

**Comment by slandelle** [comment] 2017-03-24 15:11
@harisankarh AHC 1 has reached end-of-life and is no longer maintained, so is Java 1.7. Time to explain your client that it's time to spend some money upgrading.

**Comment by harisankarh** [comment] 2017-03-25 07:16
@slandelle  Thank you for your response. I'll definitely try to explain and upgrade. Just to clarify, is the answer to the question, 'No' ? (whether 1.9.40 has a fix for this). Thanks again..

**Comment by slandelle** [comment] 2017-03-25 07:45
Answer is no.

**Comment by harisankarh** [comment] 2017-03-25 15:28
@slandelle Thank you
