### ISSUE TITLE
Grizzly 2.3.19 fails when using SSL

### ISSUE THREAD

**Issue by pablolagreca** [AsyncHttpClient/async-http-client#860] opened 2015-04-22 18:06 UTC
I'm creating this issue based on the google group discussion: https://groups.google.com/forum/#!topic/asynchttpclient/ct-6ztpTGiw

I will provide a PR to get it fix.

**Comment by lguerrin** [comment] 2015-05-11 15:29
Any update about this issue?

I have the same problem, but I can't reproduce it in a test.
This seems depend on the server configuration.

**Comment by oleksiys** [comment] 2015-05-11 18:09
Hi,

I'd appreciate if you can share the testcase.

Thanks.

WBR,
Alexey.

**Comment by lguerrin** [comment] 2015-05-11 18:58
Hi, 

I reproduce the bug only on protected server, so I cannot share the testcase.
With SSL debug, it seems that is the  remote server which closes connection:
```
main, WRITE: TLSv1 Application Data, length = 253
main, WRITE: TLSv1 Application Data, length = 256
Grizzly(20), READ: TLSv1 Alert, length = 22
Grizzly(20), RECV TLSv1 ALERT:  warning, close_notify
Grizzly(20), closeInboundInternal()
Grizzly(20), closeOutboundInternal()
Grizzly(20), SEND TLSv1 ALERT:  warning, description = close_notify
Grizzly(20), WRITE: TLSv1 Alert, length = 22
```
When I query public server like bing or google (with https), I have no problem.

Best regards,
Loïc

**Comment by oleksiys** [comment] 2015-05-11 19:03
Can you make the server public and send me privately the client side code?

**Comment by slandelle** [comment] 2015-09-11 10:35
@oleksiys What's the status of this? Can it be closed?

**Comment by oleksiys** [comment] 2015-09-11 19:10
closing the issue. pls reopen it once you have a reproducer.
thanks.

**Closed by oleksiys** 2015-09-11 19:10 UTC
Labels: Defect, Grizzly
