### ISSUE TITLE
NullPointer while processing response with no body using retrofit

### ISSUE THREAD

**Issue by OKoneva** [AsyncHttpClient/async-http-client#1577] opened 2018-09-14 11:58 UTC
OkHttpCall parseResponse fails with NullPointer trying to parse response with no body. It happens because org.asynchttpclient.extras.retrofit.AsyncHttpClientCall creates response with null body.

**Comment by slandelle** [comment] 2018-09-14 12:01
Duplicate of #1568.
IMO, this is a retrofit issue.

**Closed by slandelle** 2018-09-14 12:01 UTC
